#[cfg(target_arch = "wasm32")]
use dioxus::prelude::*;
#[cfg(target_arch = "wasm32")]
use crate::frontend::state::IntellijState;

#[cfg(target_arch = "wasm32")]
struct MockFile {
    path: &'static str,
    content: &'static str,
}

#[cfg(target_arch = "wasm32")]
const MOCK_FILES: &[MockFile] = &[
    MockFile {
        path: "src/lib.rs",
        content: r#"#![no_std]
// Telemetry Buffer package for STM32
use std::collections::VecDeque;

pub struct TelemetryBuffer {
    data: VecDeque<u32>,
}

impl TelemetryBuffer {
    pub fn new() -> Self {
        Self { data: VecDeque::new() }
    }
}
"#,
    },
    MockFile {
        path: "src/main.rs",
        content: r#"#![no_std]
#![no_main]

use cortex_m_rt::entry;
use panic_halt as _;
use stm32f4xx_hal as hal;

#[entry]
fn main() -> ! {
    let mut x = 0;
    loop {
        x += 1;
    }
}
"#,
    },
    MockFile {
        path: "Cargo.toml",
        content: r#"[package]
name = "oxide-embedded-firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
panic-halt = "0.2.0"
stm32f4xx-hal = { version = "0.16.0", features = ["stm32f405", "rt"] }
"#,
    },
    MockFile {
        path: "src/peripherals.rs",
        content: r#"// Peripheral pin layout
// GPIOA Pin 1 is mapped to PWM clock tree.
// GPIOB Pin 3 is mapped to SPI clock tree.
"#,
    },
];

#[cfg(target_arch = "wasm32")]
#[component]
pub fn ExplorerPanel() -> Element {
    let mut state: IntellijState = use_context::<IntellijState>();
    let selected = state.selected_file.read().clone();

    let current_file = MOCK_FILES.iter().find(|f| f.path == selected.as_str())
        .unwrap_or(&MOCK_FILES[0]);

    let load_into_review = move |_| {
        state.review_code.set(current_file.content.to_string());
        state.review_title.set(format!("Review of {}", current_file.path));
        state.review_desc.set("Autogenerated code audit from workspace file explorer.".to_string());
        state.active_tab.set("review".to_string());
    };

    rsx! {
        div {
            style: "background: rgba(17, 21, 32, 0.7); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 16px; overflow: hidden; display: flex; flex-direction: column; flex-grow: 1; padding: 16px; gap: 16px; max-height: calc(100vh - 120px); overflow-y: auto;",
            
            h2 {
                style: "font-size: 14px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #f1f5f9; margin: 0; text-align: left;",
                "Workspace Explorer"
            }

            div {
                style: "display: grid; grid-template-columns: 1fr 2fr; gap: 12px; flex-grow: 1; height: 320px;",
                
                // File List
                div {
                    style: "background: rgba(15, 19, 34, 0.5); border: 1px solid rgba(255, 255, 255, 0.04); border-radius: 10px; padding: 8px; display: flex; flex-direction: column; gap: 4px; overflow-y: auto;",
                    {MOCK_FILES.iter().map(|f| {
                        let is_sel = f.path == selected;
                        let item_style = if is_sel {
                            "background: rgba(6, 182, 212, 0.15); color: #22d3ee; border-radius: 6px; padding: 6px 10px; font-size: 11px; font-family: monospace; border: 1px solid rgba(6, 182, 212, 0.2); text-align: left; cursor: pointer;"
                        } else {
                            "background: transparent; color: #cbd5e1; border-radius: 6px; padding: 6px 10px; font-size: 11px; font-family: monospace; border: 1px solid transparent; text-align: left; cursor: pointer; transition: all 0.2s;"
                        };
                        rsx! {
                            button {
                                key: "{f.path}",
                                style: "{item_style}",
                                onclick: move |_| state.selected_file.set(f.path.to_string()),
                                "{f.path}"
                            }
                        }
                    })}
                }

                // File content viewer
                div {
                    style: "display: flex; flex-direction: column; gap: 8px; overflow: hidden;",
                    
                    div {
                        style: "display: flex; justify-content: space-between; align-items: center;",
                        span { style: "font-family: monospace; font-size: 11px; color: #94a3b8;", "{current_file.path}" }
                        button {
                            style: "background: rgba(6, 182, 212, 0.1); border: 1px solid rgba(6, 182, 212, 0.2); color: #22d3ee; padding: 4px 8px; border-radius: 6px; font-size: 10px; font-weight: 600; cursor: pointer;",
                            onclick: load_into_review,
                            "Load into PR Review"
                        }
                    }

                    pre {
                        style: "background: #07090f; border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 8px; padding: 12px; font-family: monospace; font-size: 10px; color: #f1f5f9; flex-grow: 1; overflow-y: auto; text-align: left; margin: 0; line-height: 1.4; white-space: pre-wrap;",
                        "{current_file.content}"
                    }
                }
            }
        }
    }
}
